# Heads-Up: This Dockerfile is *exclusively* used for CI. It is referenced by
# Jenkinsfile and should not be used by any other means.

FROM node:9.8.0

USER root

ADD package.json package-lock.json /
RUN npm install
RUN ln -s /node_modules/.bin/* /usr/local/bin/
