# Heads-Up: This Dockerfile is *exclusively* used for CI. It is referenced by
# Jenkinsfile and should not be used by any other means.

FROM node:9.8.0

USER root

RUN curl -L https://github.com/docker/compose/releases/download/1.21.2/docker-compose-$(uname -s)-$(uname -m) -o /usr/local/bin/docker-compose && chmod +x /usr/local/bin/docker-compose
ADD package.json yarn.lock /
RUN yarn install
RUN ln -f -s /node_modules/.bin/* /usr/local/bin/
WORKDIR /app
