---
peers:
    - aenode://pp_HdcpgTX2C1aZ5sjGGysFEuup67K9XiFsWqSPJs4RahEcSyF7X@node1:3015
    - aenode://pp_Dxq41rJN33j26MLqryvh7AnhuZywefWKEPBiiYu2Da2vDWLBq@node3:3015

http:
    external:
        port: 3013
    internal:
        listen_address: 0.0.0.0

websocket:
    internal:
        listen_address: 0.0.0.0

keys:
    password: "top secret"
    dir: ./keys

chain:
    persist: false

mining:
    beneficiary: "ak_2mwRmUeYmfuW93ti9HMSUJzCk1EYcQEfikVSzgo6k2VghsWhgU"
    beneficiary_reward_delay: 2
    autostart: false
    cuckoo:
        miner:
            executable: mean16s-generic
            extra_args: ""
            node_bits: 16
