#!/usr/bin/env -S ts-node --transpile-only
import ts, { factory } from 'typescript';
import { writeFileSync } from 'fs';
import { basename } from 'path';
import { txSchema } from '../src/tx/builder/schema';
import { Tag } from '../src/tx/builder/constants';

const destPath = 'src/tx/builder/schema.generated.ts';

const sourceFile = ts.createSourceFile(basename(destPath), '', ts.ScriptTarget.Latest);

function addTsDocCategory<T extends ts.Node>(node: T): T {
  return ts.addSyntheticLeadingComment(
    node,
    ts.SyntaxKind.MultiLineCommentTrivia,
    '*\n * @category transaction builder\n ',
    true,
  );
}

const list = factory.createNodeArray([
  factory.createImportDeclaration(
    undefined,
    factory.createImportClause(
      false,
      undefined,
      factory.createNamedImports([
        factory.createImportSpecifier(
          false,
          factory.createIdentifier('TxParams'),
          factory.createIdentifier('TxParamsComplex'),
        ),
        factory.createImportSpecifier(
          false,
          factory.createIdentifier('TxParamsAsync'),
          factory.createIdentifier('TxParamsAsyncComplex'),
        ),
        factory.createImportSpecifier(
          false,
          factory.createIdentifier('TxUnpacked'),
          factory.createIdentifier('TxUnpackedComplex'),
        ),
      ]),
    ),
    factory.createStringLiteral('./schema'),
    undefined,
  ),
  factory.createImportDeclaration(
    undefined,
    factory.createImportClause(
      false,
      undefined,
      factory.createNamedImports([factory.createImportSpecifier(
        false,
        undefined,
        factory.createIdentifier('Tag'),
      )]),
    ),
    factory.createStringLiteral('./constants'),
    undefined,
  ),
  ...txSchema.map((schema) => {
    const tag = Tag[schema.tag.constValue];
    const version = schema.version.constValue;
    const name = `${tag}${version}`;
    return ['TxParams', 'TxParamsAsync', 'TxUnpacked'].map((kind) => [
      factory.createTypeAliasDeclaration(
        undefined,
        factory.createIdentifier(`${kind}${name}Type`),
        undefined,
        factory.createIntersectionTypeNode([
          factory.createTypeReferenceNode(
            factory.createIdentifier(`${kind}Complex`),
            undefined,
          ),
          factory.createTypeLiteralNode([
            factory.createPropertySignature(
              undefined,
              factory.createIdentifier('tag'),
              undefined,
              factory.createTypeReferenceNode(
                factory.createQualifiedName(
                  factory.createIdentifier('Tag'),
                  factory.createIdentifier(tag),
                ),
                undefined,
              ),
            ),
            factory.createPropertySignature(
              undefined,
              factory.createIdentifier('version'),
              schema.version.constValueOptional
                ? factory.createToken(ts.SyntaxKind.QuestionToken)
                : undefined,
              factory.createLiteralTypeNode(factory.createNumericLiteral(version)),
            ),
          ]),
        ]),
      ),
      factory.createInterfaceDeclaration(
        [factory.createToken(ts.SyntaxKind.ExportKeyword)],
        factory.createIdentifier(`${kind}${name}`),
        undefined,
        [factory.createHeritageClause(
          ts.SyntaxKind.ExtendsKeyword,
          [factory.createExpressionWithTypeArguments(
            factory.createIdentifier(`${kind}${name}Type`),
            undefined,
          )],
        )],
        [],
      ),
    ])
      .flat()
      .map((node) => addTsDocCategory(node));
  }).flat(),
  ...['TxParams', 'TxParamsAsync', 'TxUnpacked'].map((kind) => (
    factory.createTypeAliasDeclaration(
      [factory.createToken(ts.SyntaxKind.ExportKeyword)],
      factory.createIdentifier(kind),
      undefined,
      factory.createUnionTypeNode(txSchema.map((schema) => {
        const tag = Tag[schema.tag.constValue];
        const version = schema.version.constValue;
        const name = `${tag}${version}`;
        return factory.createTypeReferenceNode(factory.createIdentifier(`${kind}${name}`));
      })),
    )
  ))
    .map((node) => addTsDocCategory(node)),
]);

const result = `/* eslint-disable */
// This file generated by \`npm run build:generate\`, don't edit manually.

${ts.createPrinter().printList(ts.ListFormat.MultiLine, list, sourceFile)}`;

writeFileSync(destPath, result);
