name: Build and publish docs
on:
  pull_request:
  push:
    branches: [develop]
  release:
    types: [released]
jobs:
  main:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: actions/setup-python@v5
        with:
          python-version: 3.x
          cache: pip
      - uses: actions/setup-node@v4
        with:
          node-version: 20.x
          cache: npm
      - run: pip3 install -r docs/requirements.txt
      - run: git config --global user.email "github-action@users.noreply.github.com"
      - run: git config --global user.name "GitHub Action"
      - if: github.event_name == 'pull_request'
        run: mkdocs build
      - if: github.event_name == 'push'
        run: mike deploy --push develop
      - if: github.event_name == 'release'
        run: echo "RELEASE_VERSION=${GITHUB_REF:10}" >> $GITHUB_ENV
      - if: github.event_name == 'release'
        run: mike deploy --push --update-aliases $RELEASE_VERSION latest
