name: Test & build
on:
  push:
    branches: [master, develop]
  pull_request:
jobs:
  main:
    runs-on: ubuntu-latest
    steps:
      - run: sudo apt update && sudo apt install --no-install-recommends erlang
      - uses: actions/checkout@v4
        with:
          fetch-depth: 100
      - uses: actions/setup-node@v4
        with:
          node-version: 20.x
      - uses: actions/cache@v4
        with:
          path: |
            ~/.npm
            ~/.autorest
          key: ${{ runner.os }}-npm-${{ hashFiles('**/package-lock.json') }}
      - run: npm ci
      - name: Run Commitlint
        if: github.event_name == 'pull_request'
        env:
          HEAD: ${{ github.event.pull_request.head.sha }}
          BASE: ${{ github.event.pull_request.base.sha }}
        run: npx commitlint --from $BASE --to $HEAD --verbose
      - run: npm run lint
      - run: npm run docs:examples && npm run docs:api && ./docs/build-assets.sh
        if: contains(github.event.pull_request.title, 'Release')
      - run: docker compose up -d --wait
      - run: npx nyc npm test
      - run: npx nyc report --reporter=text-lcov > coverage.lcov
      - uses: codecov/codecov-action@v4
        with:
          files: coverage.lcov
        env:
          CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
      - run: docker compose logs
        if: always()
